### ISSUE TITLE
Fix style issue with popular/active user list

### ISSUE THREAD

**Issue by wil92** [binary-coffee-dev/dcs-frontend#468]
**Description**

When the username of the user is to long, the style get broken. Check picture as example:

![image](https://user-images.githubusercontent.com/10768089/236825021-b1bf58ff-f0ae-46e4-8ffe-9fcaf93d7856.png)

**Comment by RajivRnjan** [comment]
I am interested to work on this issue under Quine. So please assign me this issue to me.

**Comment by wil92** [comment]
Sure, take a look and make a MR when is done.

I'm still creating some documentation to setting up the whole application, but in the meed time you can use the api of development and work in the frontend with that information or you can even setting-up the frontend to get the information from the current prod api.

have fun and thx for the collaboration

**Comment by RajivRnjan** [comment]
Can you please provide the way to run this web app in local host.

**Comment by wil92** [comment]
1. clone the project: `git clone git@github.com:binary-coffee-dev/dcs-frontend.git`
2. move to develop branch: `git checkout develop`
3. install dependencies: `npm i`
4. run the project to use the configurations from the development environment: `nx run blog:serve:development --watch --poll=2000 --port=4200 --host=0.0.0.0 --disable-host-check`

And it should be it, you can now navigate thrown the application with the data coming from the development deployment. If you instead want to get the information from production, you can run the command: `nx run blog:serve:production --watch --poll=2000 --port=4200 --host=0.0.0.0 --disable-host-check`.

> The only problem here, is that you can't log-in to your local environment, this is something that you can only accomplish if you have the api also setting up in your local environment.

**Comment by wil92** [comment]
Fixed already with the introduction of tailwind in the project
